### ISSUE TITLE
Unable to download version 1.1.0 with pip

### ISSUE THREAD

**Issue by McCannDahl** [tmcclintock/FrisPy#22]
Hey Tom it's McCann! Awesome repo. I ran into an issue today adding this module to a CI pipeline.

Steps to reproduce:
1. python -m venv tempvenv
2.  source ./tempvenv/Scripts/activate
3. pip install frispy
Error output
"ModuleNotFoundError: No module named 'numpy'"
![image](https://user-images.githubusercontent.com/19883817/159392583-db8c059d-29f8-42cb-969d-70c48ae97923.png)

This error occurs even if numpy is installed :/

I think the problem is that we have `import frispy` inside setup.py. Is that intended?

**Comment by tmcclintock** [comment]
@McCannDahl finally circling back to this. real life got in the way of this project :).

Can you try again with the new release? I have tested that it is installable off of PyPI.

**Comment by McCannDahl** [comment]
Thanks Tom! I had to upgrade to python 3.9 and it worked!
